# Generated by Django 5.2.7 on 2025-10-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='quocgia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
