# Generated by Django 5.2.7 on 2025-10-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shippingaddress_quocgia'),
    ]

    operations = [
        migrations.CreateModel(
            name='baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baner', models.ImageField(blank=True, null=True, upload_to='')),
                ('name_baner', models.CharField(blank=True, max_length=100, null=True)),
                ('describe_baner', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
